var first_name = "Narayan";
console.log(first_name);
var last_name = "Mitra";
console.log(last_name);
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = "10";
console.log(a);
var b = "5";
console.log(b);
var add = a + b;
console.log(add);
var subract = a - b;
console.log(subract);
var multiply = a * b;
console.log(multiply);
var divide = a / b;
console.log(divide);